import { readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const motifsDir = join(root, "public/banners/motifs");
const precacheOut = join(root, "lib/sw-precache.generated.ts");

function motifUrls(): string[] {
  return readdirSync(motifsDir)
    .filter((f) => f.endsWith(".svg"))
    .sort()
    .map((f) => `/banners/motifs/${f}`);
}

function main() {
  const motifs = motifUrls();

  writeFileSync(
    precacheOut,
    `// Auto-generated by scripts/generate-sw-precache.ts — do not edit.\n` +
      `export const SW_PRECACHE_MOTIFS: readonly string[] = ${JSON.stringify(motifs, null, 2)};\n`
  );

  console.log(`Wrote ${motifs.length} motif URLs → lib/sw-precache.generated.ts`);
}

main();
